/* Generated by tools/runes.py. Do not edit. */
#ifndef DEW_RUNEART_H
#define DEW_RUNEART_H

#include <stdint.h>

#define RUNE_ART_W 17
#define RUNE_ART_H 24
#define RUNE_ART_COUNT 24
#define RUNE_ALIAS_COUNT 18
#define RUNE_HUES 8
#define RUNE_PASTEL 25 /* percent toward nord6 */

typedef struct {
    const char *name, *meaning;
    uint32_t cp;
    const char *art[RUNE_ART_H]; /* '#' ink, '.' clear */
} RuneArt;

extern const RuneArt RUNE_ART[RUNE_ART_COUNT];        /* futhark order */
extern const char *const RUNE_ALIASES[RUNE_ALIAS_COUNT][2]; /* other spelling, name */
extern const uint8_t RUNE_HUE[RUNE_HUES];             /* rune i is nord[RUNE_HUE[i % RUNE_HUES]] */

#endif
